name: Auto merge lokalise

on:
  push:
    branches:
      - lokalise**

jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        if: ${{ github.actor == 'dev-property-pass' }}
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
